config/routes.rb
Rails.application.routes.draw do

 root to: 'landing#index'
 resources :lessons, only: [:index, :show]
 resources :vocabularies, only: [:index]

 resources :lessons do
   resources :assessments, only: [:create, :index] do
     get 'take', to: 'assessments#new', on: :member, as: :new
     get 'attempt/:attempt', to: 'assessments#show', on: :member, as: :show
   end
 end

 devise_for :users
 resources :users,  path: "/users", only: [:show]
 authenticated :user do
   root to: 'lessons#index', as: :authenticated_root
 end

 # route for admin
 namespace :admin do
   resources :users
   resources :lessons
   resources :levels
   resources :vocabularies
   resources :assessments
   resources :assessment_questions
   resources :assessment_options
   resources :assessment_answers
   root to: "users#index"
 end

 # route for engine forum
 mount Thredded::Engine => '/forum'
 devise_scope :user do 
   delete '/users/sign_out', to: 'devise/sessions#destroy'
 end
end

app/helpers/user_assessment_attempt_helper.rb
module UserAssessmentAttemptHelper
end

app/views/user_assessment_attempts/show.html.erb
<div class="container border border-primary">
	<form action='<%= user_assessment_attempt_path %>' method="post">
		<% @questions.each do |question| %>
			<% row_number = 0 %>
			<h4><%= question.question %> (correct answer is : <%= question.correct_letter %>)</h4>
			<% if question.assessment_options.length > 0 %> <!-- verification useless peut etre ... --> <!-- current_answer.answer == option.answer -->
				<% question.assessment_options.each do |option| %>
					<% if row_number <= 0 %>
						<div class='row col-xs-12 col-lg-12'>
					<% end %>
					<% current_answer = @answers.find_by(assessment_question_id: question.id) %>
					<% correct_and_selected = false %>
					<% incorrect = false %>
					<% correct_but_not_selected = false %>
					<% if current_answer.answer == option.answer && current_answer.correct%>
					<% correct_and_selected = true %>
					<% elsif current_answer.answer == option.answer && !current_answer.correct%>
					<% incorrect = true %>
					<% end %>
					<% if question.correct_answer == option.answer && !current_answer.correct %>
					<% correct_but_not_selected = true %>
					<% end %>
					<div class="card col-xs-5 col-lg-5 text-center m-1 <%= 'bg-success' if correct_and_selected %><%= 'bg-danger text-white' if incorrect %><%= 'border-success' if correct_but_not_selected %>"><%= option.letter %> <%= option.answer %></div>
					<% row_number += 1 %>
					<% if row_number >= 2 %>
						</div>
						<% row_number = 0 %>
					<% end %>
				<% end %>
					<% if row_number < 2 && row_number > 0 %>
					</div>
					<% row_number = 0 %>
					<% end %>
			<% end %>
		<% end %>
	</form>
</div>